import localFont from "next/font/local";
import "./globals.css";
import { cookies } from "next/headers";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const id = cookieStore.get("id");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative antialiased`}
      >
        <nav className="fixed w-full z-30 bg-white flex justify-between h-10 items-center px-8 border-b shadow-sm">
          <Link href="/">Chic Avenue Store</Link>
          <div>
            {id ? (
              <div className="space-x-2">
                <Link href="/order">My Orders</Link>
                <Link href="/products">My Products</Link>
                <Link href="/profile">Profile</Link>
              </div>
            ) : (
              <div className="space-x-2">
                <Link href="/auth/login">Login</Link>
                <Link href="/auth/register">Register</Link>
              </div>
            )}
          </div>
        </nav>
        <div className="pt-10">{children}</div>
      </body>
    </html>
  );
}
